name: Generate new lists

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
      - uses: actions/checkout@v2

      - name: Generate new lists
        run: |
          chmod +x generate.sh
          ./generate.sh

      - name: Push to GitHub
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git commit -am "Updated by GitHub Actions (${GITHUB_SHA::7})"
          git push -f origin ${PUSH_BRANCH} > /dev/null 2>&1
